import React from 'react';

const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image3.png`} alt='image3' />,
      category: 'bed',
      oldPrice: 35,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'AeneanRu Bristique 2',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image10.png`} alt='image10' />,
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image4.png`} alt='image4' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image6.png`} alt='image6' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image5.png`} alt='image5' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image7.png`} alt='image7' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image8.png`} alt='image8' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image9.png`} alt='image9' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image10.png`} alt='image10' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image11.png`} alt='image11' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image12.png`} alt='image12' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image13.png`} alt='image13' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: false,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image9.png`} alt='image9' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image5.png`} alt='image5' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image3.png`} alt='image3' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image4.png`} alt='image4' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image5.png`} alt='image5' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image6.png`} alt='image6' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image7.png`} alt='image7' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image8.png`} alt='image8' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image9.png`} alt='image9' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image10.png`} alt='image10' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image11.png`} alt='image11' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      photo: <img src={`${process.env.PUBLIC_URL}/images/image12.png`} alt='image12' />,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavourite: true,
      isComparable: false,
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
